### PR TITLE
Support 0.10.0 "neon" version.

### PR DESCRIPTION
**Pull request by arthurgleckler**

### CODE REVIEW

**Comment by lassik** [comment]
Thank you for updating Chibi for us!

Directories `0`, `1`, `2`, ... are meant to indicate the major version. Since the new Chibi is still at version `0.x`, can you replace the files in the `0` directory so that they use `0.10.x` instead of `0.9.x`?

**Comment by lassik** [comment]
If the installation procedure is the same as before, the only things that need to change are the tar file URL and SHA hash.

**Comment by arthurgleckler** [comment]
Oh, sorry.  I thought the version number was the version of the Docker file.

I've updated everything.  If you agree with the changes, will you squash them?

**Comment by lassik** [comment]
Thanks. Sure, LGTM.

**Comment by lassik** [comment]
I just did a `docker build` of the container on our server and verified that it starts. Unfortunately, we don't have Docker Hub automation working at the moment; everyone involved is procrastinating on establishing the scheme.org container registry.

**Comment by arthurgleckler** [comment]
On Mon, Nov 15, 2021 at 7:22 AM lassik ***@***.***> wrote:

> I just did a docker build of the container on our server and verified
> that it starts. Unfortunately, we don't have Docker Hub automation working
> at the moment; everyone involved is procrastinating on establishing the
> scheme.org container registry.
>
> Sorry, I'm new to Docker.  What are the consequences of not having that
automation?

>
>

**Comment by arthurgleckler** [comment]
On Mon, Nov 15, 2021 at 7:28 AM Arthur A. Gleckler ***@***.***>
wrote:


> Sorry, I'm new to Docker.  What are the consequences of not having that
> automation?
>

Oh, I think I understand.  Now Dockerhub doesn't have the new version of
Chibi because it doesn't automatically update itself.

I'm trying to figure out how to do it manually, at least.  I have a
Dockerhub account, but I'm guessing that I don't have the authorization to
do this,  Would you mind authorizing me or telling me what to do?  I'm
arthurgleckler on Dockerhub.

**Comment by arthurgleckler** [comment]
P.S: Rereading old messages reminded me that you're considering setting up a Docker container server separate from Docker Hub.  In the meantime, though, can I help update Docker Hub?  Would it be possible to authorize me so that I can bring the Chibi container up to date, for example?

— still a novice

**Comment by weinholt** [comment]
You see pretty legit Arthur, so I will add you to the Docker organization. ;)

Docker Hub allows only three users per organization on the free tier. One of our slots was taken by a non-functioning automation bot, which never accepted the invitation as it seems, and which I dropped now to make room for you.

**Comment by arthurgleckler** [comment]
On Wed, Nov 17, 2021 at 9:21 AM Göran Weinholt ***@***.***>
wrote:

> You see pretty legit Arthur, so I will add you to the Docker organization.
> ;)
>
Thanks!

> Docker Hub allows only three users per organization on the free tier. One
> of our slots was taken by a non-functioning automation bot, which never
> accepted the invitation as it seems, and which I dropped now to make room
> for you.
>
I will try to be more useful than that bot.  I've started by updating 0,
head, and latest for Chibi Scheme.

I was going to do MIT Scheme, too, but Chrome is giving a "Your connection
is not private" error for containers.scheme.org at the moment.  (CC-ing
Lassi.)  Has either of you made any configuration changes recently?

Also, I can see why Lassi wants us to host our own containers.  I've only
used Docker Hub for a few days now, but its constant prompts to get me to
upgrade to a paid subscription are getting tedious already.  They need to
learn a bit of subtlety from Github.

**Comment by weinholt** [comment]
> I was going to do MIT Scheme, too, but Chrome is giving a "Your connection
> is not private" error for containers.scheme.org at the moment. (CC-ing
> Lassi.) Has either of you made any configuration changes recently?

Not me. (A major benefit of me not having access is that I can't have changed anything.)

**Pull request merged**
